export default {
    questions: [
        {question: 'Cómo se crea la NIF', options: ['El CINIF investiga el proyecto de NIF, Entra el proyecto de auscultación (periodo de revisión), CINIF Recoge todas las opiniones para ver que procede, Se elabora la versión final con fecha de publicación y entrada en vigor.', 'El CINIF emite la ley, Los profesionales la revisan, ofrecen criticas al CINIF, republican la ley'], answer: 0},
        {question: 'Qué son las normas particulares', options: ['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 0},
        {question: 'Qué es el juicio Profesional', options:['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 2},
        {question: 'Qué es la supletoriedad', options: ['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 1},
        {question: 'Qué es la sustancia económica', options:['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 0},
        {question: 'Cuál describe de mejor manera el postulado de entidad económica', options: ['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 1},
        {question: 'Cuál describe de mejor manera el postulado de negocio en marcha', options: ['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 2},
        {question: 'En qué consiste el postulado de devengación contable', options: ['Que los efectos de las transacciones y eventos económicos que afectan a una entidad deben reflejarse en la información financiera de la entidad', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Establece que todos los costos y gastos de una empresa deben identificarse con el ingreso que generaron en el mismo período'], answer: 0},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Registro de eventos cuando suceden."', options: ['Devengación contable', 'Negocio en Marcha', 'Entidad económica'], answer: 0},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Postulado que obliga a la captación de la esencia económica."', options: ['Devengación cobtable', 'Sustancia económica', 'Entidad económica'], answer: 1},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Postulado que identifica y delimita al ente económico"', options: ['Sustancia económica', 'Negocio en Marcha', 'Entidad económica'], answer: 2},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Que costos y gastos estén debajo de de los ingresos."', options: ['Devengación cobtable', 'Negocio en Marcha', 'Asociación de costos y gastos con los ingresos'], answer: 2},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Que todo vaya contablemente organizado en base a las NIF, poner un orden al registro contable"', options: ['Devengación cobtable', 'Negocio en Marcha', 'Entidad económica'], answer: 1},
        {question: 'Cuál palabra describe de mejor forma el concepto: "Definir la esencia del evento."', options: ['Sustancia económica', 'Negocio en Marcha', 'Entidad económica'], answer: 0},
        {question: 'Cuál palabra describe de mejor forma el concepto: "TODO se registra en dinero."', options: ['Devengación cobtable', 'Negocio en Marcha', 'Postulado de Valuación'], answer: 2},
        {question: 'Qué organismo pertenece a "Asociaciones de contadores públicos nacionales e internacionales"', options: ['IFAC', 'FASB', 'IASB'], answer: 0},
        {question: 'Cuál sería un ejemplo de devengación', options: ['En enero la empresa consume energía eléctrica en la fábrica en un estimado de $120,000 cuyo recibo se paga hasta febrero. El gasto se registra en enero.', 'En el mes de enero la empresa vendió mercancías a sus clientes en la cantidad de $200,000. Las mercancías se adquirieron en $110,000.'], answer: 0},
        {question: 'Cuál opción describe de mejor manera el Postulado de dualidad económica', options: ['Por un lado muestra los activos de una empresa y por otro muestra los pasivos y capital', 'Los efectos financieros derivados de las transacciones, transformaciones internas y otros eventos, que afectan económicamente a la entidad, deben cuantificarse en términos monetarios', 'Todos los costos y gastos de una empresa deben identificarse con el ingreso que generaron en el mismo período'], answer: 0},
        {question: 'Cuál opción describe de mejor manera el Postulado de Valuación', options:['Los efectos financieros derivados de las transacciones, transformaciones internas y otros eventos, que afectan económicamente a la entidad, deben cuantificarse en términos monetarios', 'Todos los costos y gastos de una empresa deben identificarse con el ingreso que generaron en el mismo período', 'Ante la existencia de operaciones similares en una entidad, debe corresponder un mismo tratamiento contable, el cual debe permanecer a través del tiempo'], answer: 0},
        {question: 'Cuál opción describe de mejor manera el Postulado de Consistencia', options:['Los efectos financieros derivados de las transacciones, transformaciones internas y otros eventos, que afectan económicamente a la entidad, deben cuantificarse en términos monetarios', 'Todos los costos y gastos de una empresa deben identificarse con el ingreso que generaron en el mismo período', 'Ante la existencia de operaciones similares en una entidad, debe corresponder un mismo tratamiento contable, el cual debe permanecer a través del tiempo'], answer: 2},
        {question: 'A cuál postulado corresponde esta definición: "Los efectos financieros derivados de las transacciones, transformaciones internas y otros eventos, que afectan económicamente a la entidad, deben cuantificarse en términos monetarios."', options: ['Postulado de Valuación', 'Postulado de Devengación Contable', 'Postulado de Dualidad Económica'], answer: 0},
        {question: 'A qué concepto pertenece esta definición: "Recurso económico, bienes o derechos, propiedad de una entidad, que se espera rinda beneficios en el futuro.', options:['Activo', 'Pasivo', 'Ingresos'], answer:0},
        {question: 'A qué concepto pertenece esta definición: "Lo que la empresa debe a otras personas o entidades conocidas como acreedores, u obligaciones de entregar un bien o servicio.', options:['Activo', 'Pasivo', 'Ingresos'], answer:1},
        {question: 'A qué concepto pertenece esta definición: "Las aportaciones y las utilidades o pérdidas propiedad de los socios o accionistas.', options:['Activo', 'Capital Contable', 'Ingresos'], answer:1},
        {question: 'A qué concepto pertenece esta definición: "Los recursos que recibe la empresa por la venta de un servicio o producto en efectivo o a crédito.', options:['Activo', 'Capital Contable', 'Ingresos'], answer:2},
        {question: 'A qué concepto pertenece esta definición: "Las erogaciones que se han usado o consumido en la empresa con el fin de obtener ingresos.', options:['Activo', 'Capital Contable', 'Gastos'], answer:2},
        {question: '"Presenta la relación de recursos (activos) así como las fuentes de financiamiento (pasivo y capital) de donde se obtuvieron a una fecha determinada"', options:['Estado de Resultado Integral', 'Estado de situación financiera', 'Estado de flujos de efectivo'], answer:1},
        {question: 'Informa sobre la rentabilidad de la operación en un periodo determinado."', options:['Estado de Resultado Integral', 'Estado de situación financiera', 'Estado de flujos de efectivo'], answer:0},
        {question: '"Brinda información sobre la liquidez del negocio durante un periodo determinado"', options:['Estado de Resultado Integral', 'Estado de situación financiera', 'Estado de flujos de efectivo'], answer:2},
        {question: '"Estado financiero que muestra los cambios ocurridos en el capital contable o patrimonio de una entidad económica durante un periodo determinado."', options:['Estado de cambios en el capital contable', 'Estado de flujos de efectivo', 'Estado de situación financiera'], answer:0}





    ]
}