export default {
    questions: [
        {question: 'Cómo se crea la NIF', options: ['El CINIF investiga el proyecto de NIF, Entra el proyecto de auscultación (periodo de revisión), CINIF Recoge todas las opiniones para ver que procede, Se elabora la versión final con fecha de publicación y entrada en vigor.', 'El CINIF emite la ley, Los profesionales la revisan, ofrecen criticas al CINIF, republican la ley'], answer: 0},
        {question: 'Qué son las normas particulares', options: ['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 0},
        {question: 'Qué es el juicio Profesional', options:['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 2},
        {question: 'Qué es la supletoriedad', options: ['Establecen bases para reconocer contablemente los elementos que integran los estados financieros', 'En la ausencia de Normas de Información Financiera es otro conjunto de normas que cubre distintas a las leyes mexicanas', 'Uso de conocimientos técnicos y experiencia profesional para seleccionar la mejor opción que refleje la sustancia económica de operaciones.'], answer: 1},
        {question: 'Qué es la sustancia económica', options:['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 0},
        {question: 'Cuál describe de mejor manera el postulado de identidad económica', options: ['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 1},
        {question: 'Cuál describe de mejor manera el postulado de negocio en marcha', options: ['La esencia del negocio o empresa, se reconoce la transacción que afecta a la organización', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Consiste en asumir que la permanencia de una empresa en el mercado no tendrá límite o fin,  por lo que los estados financieros que se elaboren deben presentar los valores determinados conforme a las NIF'], answer: 2},
        {question: 'En qué consiste el postulado de devengación contable', options: ['Que los efectos de las transacciones y eventos económicos que afectan a una entidad deben reflejarse en la información financiera de la entidad', 'Indica que las operaciones y la información financiera de una organización son independientes. Identifica de quién es la información financiera que se presenta.', 'Establece que todos los costos y gastos de una empresa deben identificarse con el ingreso que generaron en el mismo período'], answer: 0},
        


    ]
}